name: node.js CI/CD 

on:
  push:
    branches: [master]

jobs:
  # test:
  #   runs-on: ubuntu-latest

  #   # strategy:

  #   #   matrix:
  #   #     node-version: [14.x]

  #   steps:
  #   - uses: actions/checkout@v2
    
  #   - name: Use Node.js 14
  #     uses: actions/setup-node@v1
  #     with:
  #       node-version: 14
    
  #   - name: npm install and test
  #     run: |
  #       npm install
  #       npm test
  #     env:
  #       CI: true

 

  dockerize-push-release:
    name: Dockerize, push and release
    # needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Heroku Container Registry
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - name: Configure to release with heroku/nodejs buildpack
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku buildpacks:set heroku/nodejs -a ${{ secrets.HEROKU_APP_NAME }}
      - name: Build image and push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:push web -a ${{ secrets.HEROKU_APP_NAME }}
      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release web -a ${{ secrets.HEROKU_APP_NAME }}
      - name: Remove heroku/nodejs buildpack
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku buildpacks:remove heroku/nodejs -a ${{ secrets.HEROKU_APP_NAME }}
